In [18]:
import pandas as pd
from keras.models import load_model
import numpy as np

class TickerReader(object):
    def __init__(self, filename):
        self.df = pd.read_csv(filename)
        self.df = self.df.drop(columns=['open', 'high', 'low', 'close', 'volume', 'dividend', 'split'])
        self.df = self.df.head(10000).sort_values(by=['time']).groupby(['id'])
        self.model = load_model('test.h5')
        
    def predict(self):
        ids = []
        for i, df in list(self.df):
#             TODO: get row count
            x = df[['adjusted_open', 'adjusted_high', 'adjusted_low', 'adjusted_close', 'adjusted_volume', 'adjusted_open']].values
            if x.shape[0] >= 60:
                ids.append([df['id'], df['time']])

        x_input = np.empty((len(ids), 60, 6), dtype=np.float32)

        current_point = 0

        for i, df in list(self.df):
            df['moving_average'] = df['adjusted_close'].rolling(5).mean()
            x = df[['adjusted_open', 'adjusted_high', 'adjusted_low', 'adjusted_close', 'adjusted_volume', 'moving_average']].values
            if x.shape[0] >= 60:
                x_input[current_point, :, :] = x[-60:, :]
            current_point += 1
            
        y = model.predict(x_input)
        return y

In [19]:
reader = TickerReader('/Users/eureyuri/Desktop/School/Brandeis/Computer-Science/149B/cosi-149b-project2/training_project2.csv')

In [20]:
from keras.models import load_model

model = load_model('test.h5')

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


In [26]:
for i, df in list(reader.df):
    x = df[['adjusted_open', 'adjusted_high', 'adjusted_low', 'adjusted_close', 'adjusted_volume', 'adjusted_open']].values
    if x.shape[0] >= 60:
        x = x[-60:, :]
        print(x.shape)
        x = x.reshape((1, 60, 6))
        y = model.predict(x)
        print(y)

(60, 6)
[[ 0.08192189  0.122981    0.24014714  0.2754598  -0.4026155  -0.05310421]]
(60, 6)
[[ 0.08192189  0.122981    0.24014714  0.2754598  -0.4026155  -0.05310421]]
(60, 6)
[[ 0.08192189  0.122981    0.24014714  0.2754598  -0.4026155  -0.05310421]]
(60, 6)
[[ 0.08192189  0.122981    0.24014714  0.2754598  -0.4026155  -0.05310421]]


In [35]:
list(reader.df)[0][1]

adjusted_open  adjusted_high  adjusted_low  adjusted_close  \
0         29.092421      29.133072     26.971804       27.357987   
1         27.988074      29.810585     27.141182       29.810585   
2         28.794315      29.559905     27.269910       27.269910   
3         27.188608      28.414907     27.100532       27.818696   
4         27.696743      28.116802     27.608667       27.906772   
5         27.778045      28.753664     27.479939       28.543635   
6         28.455558      29.092421     27.737394       28.584286   
7         28.584286      29.431177     28.374257       29.092421   
8         29.641207      30.488098     29.261799       29.898662   
9         30.447447      30.955582     30.020614       30.149341   
10        30.657476      31.463717     30.616826       30.996233   
11        30.996233      31.165611     30.020614       30.657476   
12        30.657476      30.914931     30.359371       30.616826   
13        30.657476      31.124961     30.657476       31.036884   
14        30.955582      31.124961     30.318720       30.318720   
15        30.826855      31.334990     30.068040       30.826855   
16        30.745553      30.745553     28.496209       29.133072   
17        28.455558      28.665587     27.778045       28.245529   
18        28.455558      32.520638     28.455558       32.012503   
19        31.423066      31.924426     30.786204       31.124961   
20        31.334990      31.802474     31.253688       31.761823   
21        31.633096      31.633096     31.165611       31.592445   
22        31.592445      32.222532     31.375641       32.222532   
23        32.181881      33.875665     32.141231       33.706286   
24        33.835014      36.036932     33.577559       35.779477   
25        36.755096      41.667067     36.545067       41.667067   
26        42.683337      53.564201     42.642687       48.780957   
27        51.491010      54.201063     50.305362       53.692928   
28        53.862307      54.160413     51.660388       52.378553   
29        53.354172      53.482899     45.650846       48.780957   
...             ...            ...           ...             ...   
4527      67.032278      68.472230     66.982624       68.263686   
4528      68.055141      68.611260     67.816804       68.313339   
4529      68.799944      69.743361     68.472230       69.475232   
4530      69.564608      70.319342     67.230892       69.425578   
4531      68.660914      68.889320     67.826734       68.214032   
4532      68.362993      68.909182     68.303408       68.879389   
4533      68.740360      69.008489     68.690706       68.829736   
4534      69.078004      70.438511     68.938974       70.100867   
4535      70.011490      70.349134     67.975695       68.214032   
4536      68.492092      69.107796     67.737358       68.760221   
4537      68.710567      69.514955     66.764149       68.214032   
4538      68.462300      68.690706     65.721424       65.781009   
4539      65.741286      66.535742     65.274543       65.373850   
4540      65.423503      65.790939     65.146436       65.433434   
4541      65.453295      66.417666     65.314265       66.247752   
4542      66.476158      67.078754     66.190452       66.913109   
4543      66.962763      67.280545     66.019346       66.535742   
4544      66.535742      66.694634     66.039207       66.595327   
4545      66.764149      67.191169     66.178237       66.217960   
4546      66.466227      66.625119     65.910108       66.049138   
4547      66.416574      67.389783     66.227890       67.141516   
4548      67.767150      68.035279     67.012416       67.191169   
4549      67.240823      67.578467     67.022347       67.280545   
4550      67.568536      67.667843     66.694634       66.932971   
4551      67.111723      67.399714     66.801786       67.052139   
4552      66.992555      67.071901     66.396712       66.883317   
4553      66.843594      66.982624     66.585396       66.7840

In [42]:
import numpy as np
from datetime import datetime, timedelta

ids = []
for i, df in list(reader.df):
    x = df[['adjusted_open', 'adjusted_high', 'adjusted_low', 'adjusted_close', 'adjusted_volume', 'adjusted_open']].values
    if x.shape[0] >= 60:
        ids.append([i, datetime.strptime(df['time'].iloc[-1], '%Y-%m-%d')])
print(ids)

x_input = np.empty((len(ids), 60, 6), dtype=np.float32)

current_point = 0

for i, df in list(reader.df):
    df['moving_average'] = df['adjusted_close'].rolling(5).mean()
    x = df[['adjusted_open', 'adjusted_high', 'adjusted_low', 'adjusted_close', 'adjusted_volume', 'moving_average']].values
    if x.shape[0] >= 60:
        x_input[current_point, :, :] = x[-60:, :]
    current_point += 1
    print(x)
# print(x_input)
# y = model.predict(x_input)
# y

[[0, datetime.datetime(2017, 12, 29, 0, 0)], [1, datetime.datetime(2017, 12, 29, 0, 0)], [2, datetime.datetime(2017, 12, 29, 0, 0)], [3, datetime.datetime(2014, 8, 7, 0, 0)]]
[[2.90924207e+01 2.91330715e+01 2.69718041e+01 2.73579867e+01
  1.08971000e+07            nan]
 [2.79880741e+01 2.98105848e+01 2.71411825e+01 2.98105848e+01
  4.70520000e+06            nan]
 [2.87943149e+01 2.95599049e+01 2.72699100e+01 2.72699100e+01
  4.27440000e+06            nan]
 ...
 [6.67442873e+01 6.69925550e+01 6.66847030e+01 6.68336636e+01
  1.03858500e+06 6.68972202e+01]
 [6.69726935e+01 6.70124164e+01 6.65556038e+01 6.69826243e+01
  6.07022000e+05 6.69071509e+01]
 [6.71814163e+01 6.72610388e+01 6.66141066e+01 6.66539178e+01
  1.06489500e+06 6.68275066e+01]]
[[2.2100000e+01 2.3550000e+01 2.1780000e+01 2.3000000e+01 3.2216510e+07
            nan]
 [2.2670000e+01 2.3265000e+01 2.2635800e+01 2.2910000e+01 1.0755328e+07
            nan]
 [2.2960000e+01 2.4349300e+01 2.2940000e+01 2.4150000e+01 8.0830970e+06

In [44]:
(datetime.strptime('2019-01-01', '%Y-%m-%d') + timedelta(days=7)).strftime('%Y-%m-%d')

'2019-01-08'

In [17]:
df = reader.df.head(10000).sort_values(by=['time']).groupby(['id'])
list(df)[1][1]

open     high      low  close      volume  dividend  split  \
4557  22.100  23.5500  21.7800  23.00  32216510.0       0.0    1.0   
4558  22.670  23.2650  22.6358  22.91  10755328.0       0.0    1.0   
4559  22.960  24.3493  22.9400  24.15   8083097.0       0.0    1.0   
4560  23.820  25.5000  23.5600  25.20   6878500.0       0.0    1.0   
4561  25.540  26.4100  24.8900  25.08   8377025.0       0.0    1.0   
4562  24.300  26.5900  24.3000  26.40   6469979.0       0.0    1.0   
4563  26.830  29.1400  26.0000  28.72  10675856.0       0.0    1.0   
4564  29.080  29.7000  28.3000  29.10   8189887.0       0.0    1.0   
4565  29.180  29.9900  27.6300  29.30   5337239.0       0.0    1.0   
4566  29.500  29.9400  28.6100  29.62   5156737.0       0.0    1.0   
4567  28.940  30.2300  28.8300  30.21   3668883.0       0.0    1.0   
4568  29.690  31.6900  29.6600  31.42   6150098.0       0.0    1.0   
4569  31.300  32.0200  30.7700  31.85   4693203.0       0.0    1.0   
4570  31.730  31.7700  30.1600  30.42   4421730.0       0.0    1.0   
4571  30.890  30.9800  29.5010  30.69   2986107.0       0.0    1.0   
4572  31.100  31.9100  30.5400  31.34   4182721.0       0.0    1.0   
4573  31.000  31.9300  30.0000  31.51   4112265.0       0.0    1.0   
4574  31.240  32.1900  31.1100  31.70   3109628.0       0.0    1.0   
4575  31.480  31.8000  30.7000  30.86   5121935.0       0.0    1.0   
4576  30.020  30.4999  29.7300  29.73   4927708.0       0.0    1.0   
4577  30.060  30.4400  28.8500  28.97   5131539.0       0.0    1.0   
4578  28.840  29.4200  28.6000  28.88   5006186.0       0.0    1.0   
4579  28.860  29.6250  28.7300  29.04   3870676.0       0.0    1.0   
4580  29.030  31.2768  28.8900  31.22   7034136.0       0.0    1.0   
4581  30.710  31.1900  30.2100  31.15   3248595.0       0.0    1.0   
4582  31.300  31.8900  30.7653  30.90   5778259.0       0.0    1.0   
4583  31.280  31.8400  30.8000  31.31   3064978.0       0.0    1.0   
4584  31.310  32.1100  31.0400  32.05   4344295.0       0.0    1.0   
4585  32.160  32.3500  30.8500  31.24   3416012.0       0.0    1.0   
4586  31.400  31.7300  30.0300  30.24   4215143.0       0.0    1.0   
...      ...      ...      ...    ...         ...       ...    ...   
4820  42.680  43.0800  42.0600  42.30   3351178.0       0.0    1.0   
4821  42.000  43.6000  42.0000  43.40   3569106.0       0.0    1.0   
4822  42.290  42.5500  41.7500  42.21   4846234.0       0.0    1.0   
4823  42.730  42.7300  40.2200  41.39   6258875.0       0.0    1.0   
4824  41.840  42.6800  41.7750  42.64   3254590.0       0.0    1.0   
4825  42.800  42.9000  42.0900  42.21   1306136.0       0.0    1.0   
4826  42.150  42.4200  41.4900  42.04   3091859.0       0.0    1.0   
4827  41.810  43.7500  41.2099  43.30   8604230.0       0.0    1.0   
4828  42.190  42.3200  40.8000  41.24   4938871.0       0.0    1.0   
4829  41.500  42.1600  41.1300  41.51   4407431.0       0.0    1.0   
4830  41.820  42.3000  40.5210  41.64   3750947.0       0.0    1.0   
4831  41.870  42.6000  41.5000  41.79   2709852.0       0.0    1.0   
4832  41.370  41.8600  40.9500  41.18   2855505.0       0.0    1.0   
4833  40.800  41.4900  40.3000  41.31   5437972.0       0.0    1.0   
4834  41.130  41.1900  40.2700  40.60   3426852.0       0.0    1.0   
4835  41.000  41.7700  40.9000  41.40   3696876.0       0.0    1.0   
4836  41.540  42.9800  41.5400  42.24   4053147.0       0.0    1.0   
4837  42.390  42.8800  42.1850  42.40   3421527.0       0.0    1.0   
4838  42.450  42.5700  41.7150  41.86   4146333.0       0.0    1.0   
4839  42.050  42.3750  41.9600  42.35   3684385.0       0.0    1.0   
4840  42.850  43.1400  42.2800  42.61   4536769.0       0.0    1.0   
4841  42.775  44.6900  42.7600  44.57   3175121.0       0.0    1.0   
4842  44.770  46.5400  44.6600  46.52   5960336.0       0.0    1.0   
4843  48.191  49.6700  47.6287  49.26   7163321.0       0.0    1.0   
4844  49.570  49.6800  48.7700  48.99   3055816.0       0.0    1.0   
4845  49.150  50.0

In [ ]:
from collections import default_dict
dictionary = default_dict(lambda: [])

for i, row in reader.df.sort_values(by=['time']).iterrows():
    dictionary[row['id']].append()

In [7]:
for i, row in reader.df.head(1).iterrows():
    print(row[['id', 'time']].values)
# adjusted_open	adjusted_high	adjusted_low	adjusted_close	adjusted_volume	time	

[0 '1999-11-19']
